arch:
  - amd64
  - ppc64le
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.4
install:
  - pip install coveralls
  - python setup.py install
script: 
  - coverage run --source=codicefiscale tests.py
after_success: 
  - coveralls
notifications:
  email:
    - ema@linux.it
